#!/bin/bash
# Author: Damien Berry - https://github.com/berrydamien/pingon
#
# This script is use for ping a machine (server) diring the reboot and he shows you when the machine is online.
#
# ------------------------------------------------------------------------------
# Fonction "spinner" for waiting ....
# Author: Tasos Latsas
#
# Display an awesome 'spinner' while running your long shell commands
#
# Do *NOT* call _spinner function directly.
# Use {start,stop}_spinner wrapper functions

# usage:
#   1. source this script in your's
#   2. start the spinner:
#       start_spinner [display-message-here]
#   3. run your command
#   4. stop the spinner:
#       stop_spinner [your command's exit status]
#
# Also see: test.sh
function _spinner() {
    # $1 start/stop
    #
    # on start: $2 display message
    # on stop : $2 process exit status
    #           $3 spinner function pid (supplied from stop_spinner)

    local on_success="OK"
    local on_fail="FAIL"
    local white="\e[1;37m"
    local green="\e[1;32m"
    local red="\e[1;31m"
    local nc="\e[0m"

    case $1 in
        start)
            # calculate the column where spinner and status msg will be displayed
            ## let column=$(tput cols)-${#2}-8
	    let column=$(tput cols)-${#2}-200
            # display message and position the cursor in $column column
            echo -ne ${2}
            printf "%${column}s"

            # start spinner
            i=1
            sp='\|/-'
            delay=${SPINNER_DELAY:-0.15}

            while :
            do
                printf "\b${sp:i++%${#sp}:1}"
                sleep $delay
            done
            ;;
        stop)
            if [[ -z ${3} ]]; then
                echo "spinner is not running.."
                exit 1
            fi

            kill $3 > /dev/null 2>&1

            # inform the user uppon success or failure
            echo -en "\b["
            if [[ $2 -eq 0 ]]; then
                echo -en "${green}${on_success}${nc}"
            else
                echo -en "${red}${on_fail}${nc}"
            fi
            echo -e "]"
            ;;
        *)
            echo "invalid argument, try {start/stop}"
            exit 1
            ;;
    esac
}

function start_spinner {
    # $1 : msg to display
    _spinner "start" "${1}" &
    # set global spinner pid
    _sp_pid=$!
    disown
}

function stop_spinner {
    # $1 : command exit status
    _spinner "stop" $1 $_sp_pid
    unset _sp_pid
}
# ------------------------------------------------------------------------------
ping -c 1 $1 > /dev/null 2>&1
if [ $? -eq 2 ]
                then
                echo "ERREUR : $1 unknown host"
	else
		start_spinner 'Waiting ... '
		sleep 0.3
		while :; do
			ping -c 3 $1 > /dev/null 2>&1
				if [ $? = 0 ]; then
					break
    				else
					sleep 0.3
				fi
			done
stop_spinner $?
#echo " >> ssh $1 "
fi
exit 0
